version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=LeepRNfc24eAz&IH
    volumes:
    - C://Apps/MyNote/SQL/data:/var/opt/mssql/data
    - C://Apps/MyNote/SQL/log:/var/opt/mssql/log
    - C://Apps/MyNote/SQL/secrets:/var/opt/mssql/secrets
  mynoteapi:
    environment:
        - IsDocker=true
    build:
      context: .
      dockerfile: src/MyNoteApi/Dockerfile
    depends_on:
        - db
